run:
  tests: false
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number
linters:
  disable-all: true
  enable:
    - govet # or golint
    - unused
    - varcheck 
    - errcheck