version: '3.5'
services:
    microservice:
        build: .
        image: cloud-native-go:1.0.1-alpine
        environment: 
            - PORT=9090
        ports: 
            - "9090:9090"
        expose: 
            - "9090"
        networks: 
            my_net:
                ipv4_address: 173.19.0.3
networks: 
    my_net:
        name: cloud-native-net
        driver: bridge
        ipam:
           config:
             - subnet: 173.19.0.0/16